name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Mettez le nom de votre branche principale ici

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4  # Utilise une action pour déployer vers GitHub Pages

        # Replacez les valeurs ci-dessous avec les vôtres
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Ajoutez un secret contenant un token d'accès
          BRANCH: gh-pages  # Mettez le nom de la branche de destination pour GitHub Pages
          FOLDER: ./  # Mettez le chemin du dossier à déployer, par défaut la racine du dépôt
